---
homebrew_installed_packages:
  - sdkman
  - docker
  - docker-buildx
  - docker-completion
  - docker-compose
  - jq
  - cosign
  - stow
  - git
  - opentofu
  - pinentry-mac
  - kubernetes-cli
  - helm
  - kustomize
  - kompose
  - jq
  - nvm
  - node
  - starship
  - tree
  - wget
  - pnpm
  - stow
  - colima
  - k3s
  - k3d
  - helm
  - gh
  - yarn
  - k6
  - go

homebrew_cask_apps:
  - 1password
  - 1password-cli
  - alfred
  - arc
  - chromium
  - brave-browser
  - discord
  - vscodium
  - firefox
  - font-hack-nerd-font
  - intellij-idea
  - figma
  - iterm2
  - postman
  - ngrok
  - rustrover
  - slack
  - spotify

homebrew_taps:
  - homebrew/core
  - homebrew/cask-fonts