---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']

  tasks:
    - name: Restow dotfiles
      ansible.builtin.shell: >
        stow -d {{ ansible_env.HOME }}/dotfiles -t {{ ansible_env.HOME }} --restow
